In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('master.csv',index_col=0)

In [5]:
df.head()

,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
country,,,,,,,,,,,
Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [9]:
df.shape[1]#columns

11

In [8]:
df.shape[0]#rows

27820

In [6]:
df.count()

year                  27820
sex                   27820
age                   27820
suicides_no           27820
population            27820
suicides/100k pop     27820
country-year          27820
HDI for year           8364
 gdp_for_year ($)     27820
gdp_per_capita ($)    27820
generation            27820
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27820 entries, Albania to Uzbekistan
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                27820 non-null  int64
 1   sex                 27820 non-null  object
 2   age                 27820 non-null  object
 3   suicides_no         27820 non-null  int64
 4   population          27820 non-null  int64
 5   suicides/100k pop   27820 non-null  float64
 6   country-year        27820 non-null  object
 7   HDI for year        8364 non-null   float64
 8    gdp_for_year ($)   27820 non-null  object
 9   gdp_per_capita ($)  27820 non-null  int64
 10  generation          27820 non-null  object
dtypes: float64(2), int64(4), object(5)
memory usage: 2.5+ MB

In [8]:
df.columns

Index(['year', 'sex', 'age', 'suicides_no', 'population', 'suicides/100k pop',
       'country-year', 'HDI for year', ' gdp_for_year ($) ',
       'gdp_per_capita ($)', 'generation'],
      dtype='object')

In [31]:
df.transpose()

country,Albania,Albania,Albania,Albania,Albania,Albania,Albania,Albania,Albania,Albania,...,Uzbekistan,Uzbekistan,Uzbekistan,Uzbekistan,Uzbekistan,Uzbekistan,Uzbekistan,Uzbekistan,Uzbekistan,Uzbekistan
year,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,...,2014,2014,2014,2014,2014,2014,2014,2014,2014,2014
sex,male,male,female,male,male,female,female,female,male,female,...,female,male,male,male,female,female,female,male,female,female
age,15-24 years,35-54 years,15-24 years,75+ years,25-34 years,75+ years,35-54 years,25-34 years,55-74 years,5-14 years,...,15-24 years,55-74 years,15-24 years,75+ years,25-34 years,35-54 years,75+ years,5-14 years,5-14 years,55-74 years
suicides_no,21,16,14,1,9,1,6,4,1,0,...,347,144,347,17,162,107,9,60,44,21
population,312900,308000,289700,21800,274300,35600,278800,257200,137500,311000,...,2992817,1271111,3126905,224995,2735238,3620833,348465,2762158,2631600,1438935
suicides/100k pop,6.71,5.19,4.83,4.59,3.28,2.81,2.15,1.56,0.73,0,...,11.59,11.33,11.1,7.56,5.92,2.96,2.58,2.17,1.67,1.46
country-year,Albania1987,Albania1987,Albania1987,Albania1987,Albania1987,Albania1987,Albania1987,Albania1987,Albania1987,Albania1987,...,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014,Uzbekistan2014
HDI for year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.675,0.675,0.675,0.675,0.675,0.675,0.675,0.675,0.675,0.675
gdp_for_year ($),"2,156,624,900","2,156,624,900","2,156,624,900","2,156,624,900","2,156,624,900","2,156,624,900","2,156,624,900","2,156,624,900","2,156,624,900","2,156,624,900",...,"63,067,077,179","63,067,077,179","63,067,077,179","63,067,077,179","63,067,077,179","63,067,077,179","63,067,077,179","63,067,077,179","63,067,077,179","63,067,077,179"
gdp_per_capita ($),796,796,796,796,796,796,796,796,796,796,...,2309,2309,2309,2309,2309,2309,2309,2309,2309,2309
generation,Generation X,Silent,Generation X,G.I. Generation,Boomers,G.I. Generation,Silent,Boomers,G.I. Generation,Generation X,...,Millenials,Boomers,Millenials,Silent,Millenials,Generation X,Silent,Generation Z,Generation Z,Boomers

In [42]:
i=0
while i<10:
    print(len(df.transpose().iloc[i].unique()))
    i=i+1
    
#number of unique values for each column

32
2
6
2084
25564
5298
2321
306
2321
2233

In [46]:
df.dropna()#ans 8364

,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
country,,,,,,,,,,,
Albania,1995,male,25-34 years,13,232900,5.58,Albania1995,0.619,"2,424,499,009",835,Generation X
Albania,1995,male,55-74 years,9,178000,5.06,Albania1995,0.619,"2,424,499,009",835,Silent
Albania,1995,female,75+ years,2,40800,4.90,Albania1995,0.619,"2,424,499,009",835,G.I. Generation
Albania,1995,female,15-24 years,13,283500,4.59,Albania1995,0.619,"2,424,499,009",835,Generation X
Albania,1995,male,15-24 years,11,241200,4.56,Albania1995,0.619,"2,424,499,009",835,Generation X
...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [47]:
df.dropna(axis=1)#only HDI has mssing entries.number=27820-8364=19456

,year,sex,age,suicides_no,population,suicides/100k pop,country-year,gdp_for_year ($),gdp_per_capita ($),generation
country,,,,,,,,,,
Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,"2,156,624,900",796,Generation X
Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,"2,156,624,900",796,Silent
Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,"2,156,624,900",796,Generation X
Albania,1987,male,75+ years,1,21800,4.59,Albania1987,"2,156,624,900",796,G.I. Generation
Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,"63,067,077,179",2309,Generation X
Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,"63,067,077,179",2309,Silent
Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,"63,067,077,179",2309,Generation Z
Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,"63,067,077,179",2309,Generation Z
Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,"63,067,077,179",2309,Boomers

In [48]:
df.count()

year                  27820
sex                   27820
age                   27820
suicides_no           27820
population            27820
suicides/100k pop     27820
country-year          27820
HDI for year           8364
 gdp_for_year ($)     27820
gdp_per_capita ($)    27820
generation            27820
dtype: int64